### ISSUE TITLE
Build fail of 2.4.0 (Buffer assignment error)

### ISSUE THREAD

**Issue by The-Plottwist** [rmraya/Stingray#1]
Hello, recently I encountered with this error:
```ts
ts/app.ts:106:13 - error TS2322: Type 'string' is not assignable to type 'Buffer'.
```
I solved the issue by converting this line:
```ts
var ck: Buffer = execFileSync(this.javapath, ['--module-path', 'lib', '-m', 'openxliff/com.maxprograms.server.CheckURL', 'http://localhost:8040/StingrayServer'], { cwd: app.getAppPath() });
```

to this:
```ts
var ck: Buffer = Buffer.from(execFileSync(this.javapath, ['--module-path', 'lib', '-m', 'openxliff/com.maxprograms.server.CheckURL', 'http://localhost:8040/StingrayServer'], { cwd: app.getAppPath() }));
```
TL;DR: ```execFileSync()``` does not return a ```Buffer``` space location.

My understanding is that, unlike ```readFileSync()```, no ```Buffer``` space is allocated in ```execFileSync()```. Therefore, we have to allocate a ```Buffer``` space first with ```Buffer.from()``` and then assign it. This makes sense because, to be able to read, ```readFileSync()``` has to allocate a ```Buffer``` space and read values from it.

In the case of ```execFileSync()``` however, things are different. It returns only values in the types of ```binary``` or ```string``` which represents the child process output. The ```binary``` is the key here. Even though they stated the return types of ```Buffer``` or ```string``` in the [nodejs documentation](https://nodejs.org/api/child_process.html#child_processexecfilesyncfile-args-options), I think they meant ```binary``` or ```string```, where both can be assigned to a ```Buffer```.

Other than this, the program compiles and runs correctly.

Cheers.

PS:
Nodejs version: 16.13.1
npm version: 8.1.2

**Comment by rmraya** [comment]
Hello,

This is already fixed in the private repository for Stingray; the app runs fine from the official installers. 

The fix will be transferred to the public repository on next update.
